#include "arduino_secrets.h"
// ArduinoCloudThing - Version: 1.7.3
#include <ArduinoCloudProperty.h>
#include <ArduinoCloudThing.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Pill dispenser"
  https://create.arduino.cc/cloud/things/423500f3-3614-42d4-9d62-40d97c1c3a0a 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int minutes_alarm;
  int hours_alarm;
  CloudSchedule schedule_var;
  bool alarm_state;
  int seconds_alarm;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "RTCZero.h"


RTCZero alarm;

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();


  alarm.begin();


  digitalWrite(LED_BUILTIN, HIGH);

}


void loop() {
  ArduinoCloud.update();
  // Your code here 
  Serial.print(alarm.getHours());  Serial.print(":");
  Serial.print(alarm.getMinutes());  Serial.print(":");
  Serial.println(alarm.getSeconds());
  
}

/*
  Since AlarmState is READ_WRITE variable, onAlarmStateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onAlarmStateChange()  {
  if (alarm_state == true) {

    alarm.setAlarmTime(hours_alarm, minutes_alarm, seconds_alarm);

    alarm.enableAlarm(alarm.MATCH_HHMMSS);

    alarm.attachInterrupt(alarmMatch);

  }

  else {

    alarm.disableAlarm();

    digitalWrite(LED_BUILTIN, LOW);

  }

}

void alarmMatch() {

  digitalWrite(LED_BUILTIN, HIGH);

}

/*
  Since HoursAlarm is READ_WRITE variable, onHoursAlarmChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHoursAlarmChange()  {
    alarm.setAlarmTime(hours_alarm, minutes_alarm, seconds_alarm);
}

/*
  Since MinutesAlarm is READ_WRITE variable, onMinutesAlarmChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMinutesAlarmChange()  {
  alarm.setAlarmTime(hours_alarm, minutes_alarm, seconds_alarm);
}


/*
  Since SecondsAlarm is READ_WRITE variable, onSecondsAlarmChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSecondsAlarmChange()  {
  alarm.setAlarmTime(hours_alarm, minutes_alarm, seconds_alarm);
}




/*
  Since ScheduleVar is READ_WRITE variable, onScheduleVarChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onScheduleVarChange()  {
  // Add your code here to act upon ScheduleVar change
}
